export type ActivityKind =
  | "TIER_UNLOCK"
  | "DEFENSE"
  | "MM_UPDATE"
  | "VOLUME_BOT"
  | "REWARDS_DISTRIBUTION"
  | "VOTE_OPENED"
  | "VOTE_CLOSED"
  | "VOTE_EXECUTED"
  | "BUY_BURN"
  | "AIRDROP"
  | "REINFORCE_MM"
  | "TREASURY_TRADE"
  | "PULSE_WARS"
  | "HOLD"
  | "BOUNTY_OPENED"
  | "BOUNTY_FULFILLED"
  | "TWEET_BONUS_AWARDED"
  | "NOTABLE_BUY"
  | "SAFETY_HALT"
  | "DRY_RUN_NOTICE";

export const ACTIVITY_KINDS: readonly ActivityKind[] = [
  "TIER_UNLOCK",
  "DEFENSE",
  "MM_UPDATE",
  "VOLUME_BOT",
  "REWARDS_DISTRIBUTION",
  "VOTE_OPENED",
  "VOTE_CLOSED",
  "VOTE_EXECUTED",
  "BUY_BURN",
  "AIRDROP",
  "REINFORCE_MM",
  "TREASURY_TRADE",
  "PULSE_WARS",
  "HOLD",
  "BOUNTY_OPENED",
  "BOUNTY_FULFILLED",
  "TWEET_BONUS_AWARDED",
  "NOTABLE_BUY",
  "SAFETY_HALT",
  "DRY_RUN_NOTICE",
] as const;
