export type ActivityKind =
  | "TIER_UNLOCK"
  | "VOTE_OPENED"
  | "VOTE_CLOSED"
  | "VOTE_EXECUTED"
  | "BUY_BURN"
  | "AIRDROP"
  | "VOLUME_BOT"
  | "BOUNTY_OPENED"
  | "BOUNTY_FULFILLED"
  | "TWEET_BONUS_AWARDED"
  | "NOTABLE_BUY"
  | "SAFETY_HALT"
  | "DRY_RUN_NOTICE"
  | "AI_INSIGHT"
  | "AUTONOMOUS_ACTION"
  | "AUTONOMOUS_PASS"
  | "MIND_THOUGHT"
  | "CONSTITUTION_AMENDED"
  | "PULSE_TIP";

export const ACTIVITY_KINDS: readonly ActivityKind[] = [
  "TIER_UNLOCK",
  "VOTE_OPENED",
  "VOTE_CLOSED",
  "VOTE_EXECUTED",
  "BUY_BURN",
  "AIRDROP",
  "VOLUME_BOT",
  "BOUNTY_OPENED",
  "BOUNTY_FULFILLED",
  "TWEET_BONUS_AWARDED",
  "NOTABLE_BUY",
  "SAFETY_HALT",
  "DRY_RUN_NOTICE",
  "AI_INSIGHT",
  "AUTONOMOUS_ACTION",
  "AUTONOMOUS_PASS",
  "MIND_THOUGHT",
  "CONSTITUTION_AMENDED",
  "PULSE_TIP",
] as const;
